name: Publish
on:
  push:
    branches:
      - production

jobs:
  publish:
    name: Production
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
      - run: npm ci
      - uses: actions/cache/restore@v4
        with:
          path: |
            node_modules/.astro
          key: static
      - run: npm run build
        name: Build
        env:
          NODE_OPTIONS: --max-old-space-size=4096
      - run: npx wrangler deploy
        name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            node_modules/.astro
          key: static
