on:
  push:
    branches-ignore:
      - production

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    name: Publish Preview
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
      - run: npm ci
      - uses: actions/cache/restore@v4
        with:
          path: |
            node_modules/.astro
          key: static
      - run: npm run build
        name: Build
        env:
          NODE_OPTIONS: --max-old-space-size=4096
      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          SHORT_SHA=$(git rev-parse --short=8 HEAD)
          BRANCH_SLUG=$(git rev-parse --abbrev-ref HEAD | iconv -c -t ascii//TRANSLIT | sed -E 's/[~^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+|-+$//g' | tr A-Z a-z)

          npx wrangler deploy --dispatch-namespace preview-deployments --name $SHORT_SHA
          npx wrangler deploy --dispatch-namespace preview-deployments --name $BRANCH_SLUG
      - name: Post preview URL on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx tsx bin/post-preview-url-comment/index.ts
        continue-on-error: true
      - uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            node_modules/.astro
          key: static
